version: '3.8'
services:
  db:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: pttk
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: